import os
import re
import pandas as pd

def run_deseq2_stress_vs_control(split_dir, output_dir, n_clusters=6):
    """Line 1: Executes DESeq2 in R via rpy2 for Stress vs Control comparison."""
    from rpy2.robjects import r
    os.makedirs(output_dir, exist_ok=True)
    
    r_code = f"""
    library(DESeq2)
    input_path <- "{split_dir.replace('\\', '/')}"
    output_dir <- "{output_dir.replace('\\', '/')}"
    
    for (cluster_id in 0:{n_clusters-1}) {{
        c_dir <- file.path(input_path, paste0("cluster", cluster_id))
        g_ctrl_file <- file.path(c_dir, paste0("G_control_cluster", cluster_id, ".csv"))
        if (!file.exists(g_ctrl_file)) next
        
        G_control <- read.csv(g_ctrl_file, row.names=1)
        A_control <- read.csv(file.path(c_dir, paste0("A_control_cluster", cluster_id, ".csv")), row.names=1)
        G_stress  <- read.csv(file.path(c_dir, paste0("G_stress_cluster", cluster_id, ".csv")), row.names=1)
        A_stress  <- read.csv(file.path(c_dir, paste0("A_stress_cluster", cluster_id, ".csv")), row.names=1)
        
        counts <- cbind(G_control, G_stress, A_control, A_stress)
        num_ctrl <- ncol(G_control)
        num_stress <- ncol(G_stress)
        
        design <- data.frame(
            Trt = factor(rep(c(rep("control", num_ctrl), rep("stress", num_stress)), 2), levels = c("control", "stress")),
            Type = factor(c(rep("Edit_G", (num_ctrl + num_stress)), rep("Base_A", (num_ctrl + num_stress))), levels = c("Base_A", "Edit_G"))
        )
        
        dds <- DESeqDataSetFromMatrix(countData = round(as.matrix(counts)), colData = design, design = ~ Type + Trt + Type:Trt)
        
        total_coverage <- cbind((G_control + A_control), (G_stress + A_stress))
        log_data <- log(as.matrix(total_coverage))
        log_data[is.infinite(log_data)] <- NA
        log_s <- log_data - rowMeans(log_data, na.rm = TRUE)
        sf <- exp(apply(log_s, 2, function(x) median(x, na.rm = TRUE)))
        sizeFactors(dds) <- rep(sf, 2)
        
        dds <- DESeq(dds, test = "Wald", quiet = TRUE)
        res <- results(dds, name = "TypeEdit_G.Trtstress")
        
        write.csv(as.data.frame(res), file = file.path(output_dir, paste0("StressVsCtrl_Cluster", cluster_id, "_DESeq2_Results.csv")))
    }}
    """
    r(r_code)

def filter_stress_deseq2_results(deseq2_dir, output_dir, p_thresh=0.05, lfc_thresh=1.0, n_clusters=6):
    """Line 1: Cleans 'X' prefixes from R, filters by P-value and Log2FC, and exports."""
    os.makedirs(output_dir, exist_ok=True)
    
    for c in range(n_clusters):
        file_path = os.path.join(deseq2_dir, f"StressVsCtrl_Cluster{c}_DESeq2_Results.csv")
        if not os.path.exists(file_path): continue
        
        # 1. Clean 'X' prefix generated by R
        df = pd.read_csv(file_path, index_col=0)
        df.index = [re.sub(r'^X(\d)', r'\1', str(idx)) for idx in df.index]
        
        # 2. Filter logic: p < threshold AND |log2FC| > threshold
        df_sig = df.dropna(subset=['pvalue', 'log2FoldChange'])
        df_sig = df_sig[(df_sig['pvalue'] < p_thresh) & (df_sig['log2FoldChange'].abs() > lfc_thresh)].copy()
        df_final = df_sig[['pvalue', 'log2FoldChange']].sort_values(by='log2FoldChange', ascending=False)
        
        # 3. Save to CSV and TXT
        df_final.to_csv(os.path.join(output_dir, f"Cluster{c}_Significant_Sites.csv"))
        with open(os.path.join(output_dir, f"Cluster{c}_sites_list.txt"), 'w') as f:
            for site in df_final.index: f.write(f"{site}\n")


def run_deseq2_onlyC_cluster_vs_others(input_dir, output_dir, n_clusters=6):
    """Executes DESeq2 in R (~ Type + Group + Type:Group) for Control samples."""
    from rpy2.robjects import r
    os.makedirs(output_dir, exist_ok=True)
    
    r_code = f"""
    library(DESeq2)
    input_path <- "{input_dir.replace('\\', '/')}"
    output_dir <- "{output_dir.replace('\\', '/')}"
    
    for (cluster_id in 0:{n_clusters-1}) {{
        file_cluster <- file.path(input_path, paste0("cluster", cluster_id), paste0("cluster", cluster_id, "_filtered.csv"))
        file_except  <- file.path(input_path, paste0("no_cluster", cluster_id), paste0("no_cluster", cluster_id, "_filtered.csv"))
        
        if (!file.exists(file_cluster)) next
        
        data_cluster <- t(read.csv(file_cluster, row.names=1))
        data_except  <- t(read.csv(file_except, row.names=1))
        
        G_cluster <- data_cluster[, grep("_G_", colnames(data_cluster)), drop=FALSE]
        A_cluster <- data_cluster[, grep("_A_", colnames(data_cluster)), drop=FALSE]
        G_except  <- data_except[, grep("_G_", colnames(data_except)), drop=FALSE]
        A_except  <- data_except[, grep("_A_", colnames(data_except)), drop=FALSE]
        
        counts <- cbind(G_except, G_cluster, A_except, A_cluster)
        num_cluster <- ncol(G_cluster)
        num_except  <- ncol(G_except)
        
        design <- data.frame(
            Group = factor(rep(c(rep("Except", num_except), rep("Cluster", num_cluster)), 2), levels = c("Except", "Cluster")),
            Type  = factor(c(rep("Edit_G", (num_except + num_cluster)), rep("Base_A", (num_except + num_cluster))), levels = c("Base_A", "Edit_G"))
        )
        
        dds <- DESeqDataSetFromMatrix(countData = round(as.matrix(counts)), colData = design, design = ~ Type + Group + Type:Group)
        
        total_coverage <- cbind((G_except + A_except), (G_cluster + A_cluster))
        log_data <- log(as.matrix(total_coverage))
        log_data[is.infinite(log_data)] <- NA
        log_s <- log_data - rowMeans(log_data, na.rm = TRUE)
        sf <- exp(apply(log_s, 2, function(x) median(x, na.rm = TRUE)))
        sizeFactors(dds) <- rep(sf, 2)
        
        dds <- DESeq(dds, test = "Wald", quiet = TRUE)
        res <- results(dds, name = "TypeEdit_G.GroupCluster")
        
        write.csv(as.data.frame(res), file = file.path(output_dir, paste0("OnlyC_Cluster", cluster_id, "_DESeq2_Results.csv")))
    }}
    """
    try:
        r(r_code)
    except Exception as e:
        print(f"❌ DESeq2 execution failed: {e}")

def filter_onlyC_deseq2_results(deseq2_dir, output_dir, p_thresh=0.05, lfc_thresh=1.0, n_clusters=6):
    """Removes 'X' prefixes, filters significant sites, and exports."""
    os.makedirs(output_dir, exist_ok=True)
    
    for c in range(n_clusters):
        file_path = os.path.join(deseq2_dir, f"OnlyC_Cluster{c}_DESeq2_Results.csv")
        if not os.path.exists(file_path): continue
        
        df = pd.read_csv(file_path, index_col=0)
        df.index = [re.sub(r'^X(\d)', r'\1', str(idx)) for idx in df.index]
        df.to_csv(file_path)
        
        df_sig = df.dropna(subset=['pvalue', 'log2FoldChange'])
        df_sig = df_sig[(df_sig['pvalue'] < p_thresh) & (df_sig['log2FoldChange'].abs() > lfc_thresh)].copy()
        df_final = df_sig[['pvalue', 'log2FoldChange']].sort_values(by='log2FoldChange', ascending=False)
        
        df_final.to_csv(os.path.join(output_dir, f"Cluster{c}_Significant_Sites.csv"))
        with open(os.path.join(output_dir, f"Cluster{c}_sites_list.txt"), 'w') as f:
            for site in df_final.index: f.write(f"{site}\n")
            
        print(f"✅ Cluster {c}: Retained {len(df_final)} significant sites.")